package io.github.rossmci.rsaquiz;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import java.util.ResourceBundle;
import javax.swing.Timer;

/**
 *
 * @author Ross Mcinerney
 */
public class HeadingPanel extends javax.swing.JPanel
{

	private void initClock()
	{
		Timer timer = new Timer(1000, updateClockAction);
		timer.start();
	}

	ActionListener updateClockAction = new ActionListener()
	{
		@Override
		public void actionPerformed(ActionEvent e)
		{
			timeDisplayLabel.setText(new Date().toString());
		}
	};

	/**
	 * Creates new form HeadingPanel
	 */
	public HeadingPanel()
	{
		this.framesResourceBundle = ResourceBundle.getBundle("bundles/Frames");
		initComponents();
		initClock();
	}

	public HeadingPanel(RsaQuizManger rsaQuiz)
	{
		this.rsaQuizManger = rsaQuiz;
		this.framesResourceBundle = ResourceBundle.getBundle("bundles/Frames", rsaQuiz.getLocale());
		initComponents();
		initClock();
	}

	public RsaQuizManger getRsaQuizManger()
	{
		return rsaQuizManger;
	}

	public void setRsaQuizManger(RsaQuizManger rsaQuizManger)
	{
		this.rsaQuizManger = rsaQuizManger;
	}

	public void reloadLocaleResource()
	{
		this.framesResourceBundle = ResourceBundle.getBundle("bundles/Frames", rsaQuizManger.getLocale());

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private ResourceBundle framesResourceBundle;
	private RsaQuizManger rsaQuizManger;

	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        optionsjButton = new javax.swing.JButton();
        imagelabel = new javax.swing.JLabel();
        timeDisplayLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 51, 51));

        optionsjButton.setText("Options");
        optionsjButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                optionsjButtonActionPerformed(evt);
            }
        });

        imagelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsa-logo.png"))); // NOI18N

        timeDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeDisplayLabel.setText("timeDisplay");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(imagelabel)
                .addGap(18, 18, 18)
                .addComponent(timeDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionsjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(optionsjButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(timeDisplayLabel)
                        .addGap(16, 16, 16))
                    .addComponent(imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void optionsjButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_optionsjButtonActionPerformed
    {//GEN-HEADEREND:event_optionsjButtonActionPerformed
		this.getRsaQuizManger().setLanguageMenuVisible(true);
    }//GEN-LAST:event_optionsjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagelabel;
    private javax.swing.JButton optionsjButton;
    private javax.swing.JLabel timeDisplayLabel;
    // End of variables declaration//GEN-END:variables
}
