package io.github.rossmci.rsaquiz;

import java.util.ResourceBundle;

/**
 *
 * @author Ross Mcinerney
 */
public class LanguagePanel extends RsaQuizPanel
{

	public LanguagePanel()
	{
		initComponents();
	}

	@Override
	public void reloadLocaleResource()
	{
		this.framesResourceBundle = ResourceBundle.getBundle("bundles/Frames", this.getRsaQuizManger().getLocale());

		ieToggleButton.setToolTipText(framesResourceBundle.getString("LanguageMenu.ieToggleButton.toolTipText")); // NOI18N
		enToggleButton.setToolTipText(framesResourceBundle.getString("LanguageMenu.enToggleButton.toolTipText")); // NOI18N
		frToggleButton.setToolTipText(framesResourceBundle.getString("LanguageMenu.frToggleButton.toolTipText")); // NOI18N
	}

	private void changeAppLocale(String locale)
	{
		this.setVisible(false);
		this.getRsaQuizManger().setLocale(locale);
		this.getRsaQuizManger().reloadLocaleResource();
		this.getRsaQuizManger().setQuizVisible(true);
	}

	/**
	 * /**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        frToggleButton = new javax.swing.JToggleButton();
        ieToggleButton = new javax.swing.JToggleButton();
        enToggleButton = new javax.swing.JToggleButton();

        setPreferredSize(new java.awt.Dimension(690, 542));

        frToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/fr.png"))); // NOI18N
        frToggleButton.setToolTipText(framesResourceBundle.getString("LanguageMenu.frToggleButton.toolTipText")); // NOI18N
        frToggleButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                frToggleButtonActionPerformed(evt);
            }
        });

        ieToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/ie.png"))); // NOI18N
        ieToggleButton.setToolTipText(framesResourceBundle.getString("LanguageMenu.ieToggleButton.toolTipText")); // NOI18N
        ieToggleButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ieToggleButtonActionPerformed(evt);
            }
        });

        enToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/en.png"))); // NOI18N
        enToggleButton.setToolTipText(framesResourceBundle.getString("LanguageMenu.enToggleButton.toolTipText")); // NOI18N
        enToggleButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                enToggleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(frToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ieToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(enToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ieToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(280, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void frToggleButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_frToggleButtonActionPerformed
    {//GEN-HEADEREND:event_frToggleButtonActionPerformed
		changeAppLocale("fr");
    }//GEN-LAST:event_frToggleButtonActionPerformed


    private void ieToggleButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ieToggleButtonActionPerformed
    {//GEN-HEADEREND:event_ieToggleButtonActionPerformed
		changeAppLocale("ie");
    }//GEN-LAST:event_ieToggleButtonActionPerformed

    private void enToggleButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_enToggleButtonActionPerformed
    {//GEN-HEADEREND:event_enToggleButtonActionPerformed
		changeAppLocale("en");
    }//GEN-LAST:event_enToggleButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton enToggleButton;
    private javax.swing.JToggleButton frToggleButton;
    private javax.swing.JToggleButton ieToggleButton;
    // End of variables declaration//GEN-END:variables
}
