package io.github.rossmci.rsaquiz;

import java.util.ResourceBundle;
import javax.swing.JToggleButton;

public class QuizPanel extends RsaQuizPanel
{

	public QuizPanel()
	{
		initComponents();
		buttons = new JToggleButton[]
		{
			userOptionjToggleButton0,
			userOptionjToggleButton1,
			userOptionjToggleButton2
		};
	}

	@Override
	public void reloadLocaleResource()
	{
		this.framesResourceBundle = ResourceBundle.getBundle("bundles/Frames", this.getRsaQuizManger().getLocale());
		backjButton.setText(framesResourceBundle.getString("QuizFrame.BACKButton.text")); // NOI18N
		nextjButton.setText(framesResourceBundle.getString("QuizFrame.NEXTButton.text")); // NOI18N
        SubmitAnswerjButton.setText(framesResourceBundle.getString("QuizFrame.SUBMITTESTButton.text")); // NOI18N
		instructionLabel.setText(framesResourceBundle.getString("QuizFrame.instructionLabel.text")); // NOI18N
	}
	int currentIndex;
	final JToggleButton[] buttons;

	private void checkAnswer(int selectedOptionIndex)
	{
		unToogleButtons();
		this.buttons[selectedOptionIndex].setSelected(true);

		var userData = this.getUserData();
		var question = userData.getQuizQuestions().get(currentIndex);

		boolean isAnswerCorrect = question.isSelectedAnswerCorrect(selectedOptionIndex);
		userData.getGivenAnswers()[currentIndex] = selectedOptionIndex;
		userData.getUserQuizResults()[currentIndex] = isAnswerCorrect;
	}

	public void initQuiz()
	{
		currentIndex = -1;
		loadNextQuestion();// Will get the first question
	}

	private void loadNextQuestion()
	{
		currentIndex++;
		loadQuestion();
	}

	private void loadPreviousQuestion()
	{
		currentIndex--;
		loadQuestion();
	}

	private void loadQuestion()
	{
		manageNavigationButtons();

		var question = this.getUserData().getQuizQuestions().get(currentIndex);
		loadQuestion(question);
		this.counterLabel.setText("" + (currentIndex + 1));
	}

	private void manageNavigationButtons()
	{
		int testSize = this.getRsaQuizManger().getUser().getUserData().getQuizQuestions().size() -1;
		this.backjButton.setEnabled(currentIndex != 0);
		this.nextjButton.setEnabled(currentIndex != testSize);
	}

	private void loadQuestion(RsaSignQuestion question)
	{
		var questionsResourceBundle = ResourceBundle.getBundle("bundles/questions", this.getRsaQuizManger().getLocale());

		String key = question.getImageName().replaceAll(".gif", "").replaceAll(" ", "");
		this.questionLabel.setText(questionsResourceBundle.getString(key));

		for (int index = 0; index < 3; index++)
		{
			buttons[index].setIcon(new javax.swing.ImageIcon(question.getOptions().get(index)));
		}
		loadSavedAnswer(currentIndex);
	}

	private void loadSavedAnswer(int currentIndex)
	{
		int answerIndex = getUserData().getGivenAnswers()[currentIndex];
		if (answerIndex == -1)
		{
			unToogleButtons();
		}
		else
		{
			unToogleButtons();
			this.buttons[answerIndex].setSelected(true);
		}
	}

	private void unToogleButtons()
	{
		for (JToggleButton button : buttons)
		{
			button.setSelected(false);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mainPanel = new javax.swing.JPanel();
        imagelabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        pictureQuestionPanel = new javax.swing.JPanel();
        instructionLabel = new javax.swing.JLabel();
        userOptionjToggleButton0 = new javax.swing.JToggleButton();
        userOptionjToggleButton1 = new javax.swing.JToggleButton();
        userOptionjToggleButton2 = new javax.swing.JToggleButton();
        questionLabel = new javax.swing.JLabel();
        symbolLabel = new javax.swing.JLabel();
        maxLabel = new javax.swing.JLabel();
        counterLabel = new javax.swing.JLabel();
        SubmitAnswerjButton = new javax.swing.JButton();
        nextjButton = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(687, 590));

        mainPanel.setBackground(new java.awt.Color(255, 51, 51));
        mainPanel.setPreferredSize(new java.awt.Dimension(687, 542));

        imagelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsa-logo.png"))); // NOI18N

        timeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(255, 255, 255));
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLabel.setText("17:00"); // NOI18N

        pictureQuestionPanel.setBackground(new java.awt.Color(255, 255, 255));
        pictureQuestionPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(255, 51, 51)));

        instructionLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        instructionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructionLabel.setText(framesResourceBundle.getString("QuizFrame.instructionLabel.text")); // NOI18N

        userOptionjToggleButton0.setBackground(new java.awt.Color(255, 255, 255));
        userOptionjToggleButton0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signs/motorway_signs/Advance direction sign.gif"))); // NOI18N
        userOptionjToggleButton0.setBorder(null);
        userOptionjToggleButton0.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                userOptionjToggleButton0ActionPerformed(evt);
            }
        });

        userOptionjToggleButton1.setBackground(new java.awt.Color(255, 255, 255));
        userOptionjToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signs/tourist_signs/Pedestrian sign to a tourist attraction.gif"))); // NOI18N
        userOptionjToggleButton1.setBorder(null);
        userOptionjToggleButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                userOptionjToggleButton1ActionPerformed(evt);
            }
        });

        userOptionjToggleButton2.setBackground(new java.awt.Color(255, 255, 255));
        userOptionjToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signs/regulatory_signs/Clearway.gif"))); // NOI18N
        userOptionjToggleButton2.setBorder(null);
        userOptionjToggleButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                userOptionjToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pictureQuestionPanelLayout = new javax.swing.GroupLayout(pictureQuestionPanel);
        pictureQuestionPanel.setLayout(pictureQuestionPanelLayout);
        pictureQuestionPanelLayout.setHorizontalGroup(
            pictureQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pictureQuestionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userOptionjToggleButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(userOptionjToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(userOptionjToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(instructionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pictureQuestionPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {userOptionjToggleButton0, userOptionjToggleButton1, userOptionjToggleButton2});

        pictureQuestionPanelLayout.setVerticalGroup(
            pictureQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pictureQuestionPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(instructionLabel)
                .addGap(18, 18, 18)
                .addGroup(pictureQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userOptionjToggleButton0, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .addComponent(userOptionjToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userOptionjToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        questionLabel.setBackground(new java.awt.Color(255, 51, 51));
        questionLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        questionLabel.setForeground(new java.awt.Color(255, 255, 255));
        questionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionLabel.setText("Test Question");

        symbolLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        symbolLabel.setForeground(new java.awt.Color(255, 255, 255));
        symbolLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        symbolLabel.setText("/"); // NOI18N

        maxLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        maxLabel.setForeground(new java.awt.Color(255, 255, 255));
        maxLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maxLabel.setText("20"); // NOI18N

        counterLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        counterLabel.setForeground(new java.awt.Color(255, 255, 255));
        counterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        counterLabel.setText("1"); // NOI18N

        SubmitAnswerjButton.setBackground(new java.awt.Color(0, 0, 0));
        SubmitAnswerjButton.setForeground(new java.awt.Color(255, 255, 255));
        SubmitAnswerjButton.setText(framesResourceBundle.getString("QuizFrame.SUBMITTESTButton.text")); // NOI18N
        SubmitAnswerjButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SubmitAnswerjButtonActionPerformed(evt);
            }
        });

        nextjButton.setBackground(new java.awt.Color(0, 0, 0));
        nextjButton.setForeground(new java.awt.Color(255, 255, 255));
        nextjButton.setText(framesResourceBundle.getString("QuizFrame.NEXTButton.text")); // NOI18N
        nextjButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nextjButtonActionPerformed(evt);
            }
        });

        backjButton.setBackground(new java.awt.Color(0, 0, 0));
        backjButton.setForeground(new java.awt.Color(255, 255, 255));
        backjButton.setText(framesResourceBundle.getString("QuizFrame.BACKButton.text")); // NOI18N
        backjButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                backjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pictureQuestionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(questionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backjButton)
                .addGap(62, 62, 62)
                .addComponent(counterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(symbolLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maxLabel)
                .addGap(62, 62, 62)
                .addComponent(nextjButton)
                .addGap(50, 50, 50)
                .addComponent(SubmitAnswerjButton)
                .addGap(49, 49, 49))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(timeLabel)))
                .addGap(32, 32, 32)
                .addComponent(pictureQuestionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(questionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitAnswerjButton)
                    .addComponent(nextjButton)
                    .addComponent(counterLabel)
                    .addComponent(symbolLabel)
                    .addComponent(maxLabel)
                    .addComponent(backjButton))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitAnswerjButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SubmitAnswerjButtonActionPerformed
    {//GEN-HEADEREND:event_SubmitAnswerjButtonActionPerformed
		this.getRsaQuizManger().setFeedBackVisible(true);

    }//GEN-LAST:event_SubmitAnswerjButtonActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_backjButtonActionPerformed
    {//GEN-HEADEREND:event_backjButtonActionPerformed
		unToogleButtons();
		loadPreviousQuestion();
    }//GEN-LAST:event_backjButtonActionPerformed

    private void nextjButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nextjButtonActionPerformed
    {//GEN-HEADEREND:event_nextjButtonActionPerformed
		unToogleButtons();
		loadNextQuestion();
    }//GEN-LAST:event_nextjButtonActionPerformed

    private void userOptionjToggleButton0ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_userOptionjToggleButton0ActionPerformed
    {//GEN-HEADEREND:event_userOptionjToggleButton0ActionPerformed
		checkAnswer(0);

    }//GEN-LAST:event_userOptionjToggleButton0ActionPerformed

    private void userOptionjToggleButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_userOptionjToggleButton1ActionPerformed
    {//GEN-HEADEREND:event_userOptionjToggleButton1ActionPerformed
		checkAnswer(1);
    }//GEN-LAST:event_userOptionjToggleButton1ActionPerformed

    private void userOptionjToggleButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_userOptionjToggleButton2ActionPerformed
    {//GEN-HEADEREND:event_userOptionjToggleButton2ActionPerformed
		checkAnswer(2);
    }//GEN-LAST:event_userOptionjToggleButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SubmitAnswerjButton;
    private javax.swing.JButton backjButton;
    private javax.swing.JLabel counterLabel;
    private javax.swing.JLabel imagelabel;
    public static javax.swing.JLabel instructionLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel maxLabel;
    private javax.swing.JButton nextjButton;
    private javax.swing.JPanel pictureQuestionPanel;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JLabel symbolLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JToggleButton userOptionjToggleButton0;
    private javax.swing.JToggleButton userOptionjToggleButton1;
    private javax.swing.JToggleButton userOptionjToggleButton2;
    // End of variables declaration//GEN-END:variables

}
